// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFl_3ipOWxSxcSw_cgaprjqm2_3HonSkY',
    appId: '1:37539554666:web:daa0155ca44716e0ff7113',
    messagingSenderId: '37539554666',
    projectId: 'pos-tycoon',
    authDomain: 'pos-tycoon.firebaseapp.com',
    storageBucket: 'pos-tycoon.firebasestorage.app',
    measurementId: 'G-KGXBS96BMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQNdsP8TtNBS-MJ6hggs1V8e_Awn4ki9I',
    appId: '1:37539554666:android:1957b362b63e6136ff7113',
    messagingSenderId: '37539554666',
    projectId: 'pos-tycoon',
    storageBucket: 'pos-tycoon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlR2Wk_ga30IAtaua6hWDkszEUeK_tQxg',
    appId: '1:37539554666:ios:1302c920c3c36a9eff7113',
    messagingSenderId: '37539554666',
    projectId: 'pos-tycoon',
    storageBucket: 'pos-tycoon.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFl_3ipOWxSxcSw_cgaprjqm2_3HonSkY',
    appId: '1:37539554666:web:37874cc79e95b54eff7113',
    messagingSenderId: '37539554666',
    projectId: 'pos-tycoon',
    authDomain: 'pos-tycoon.firebaseapp.com',
    storageBucket: 'pos-tycoon.firebasestorage.app',
    measurementId: 'G-QKC4TZ4XSW',
  );
}
