import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pos/components/ui/shimmer_effect.dart';
import 'package:pos/models/purchase.dart';
import 'package:pos/providers/product_provider.dart';
import 'package:pos/providers/supplier_provider.dart';
import 'package:pos/widget/purchase_form_dialogue.dart';
import 'package:provider/provider.dart';
import 'package:pos/l10n/app_localizations.dart';
import '../components/ui/custom_button.dart';
import '../components/ui/custom_card.dart';
import '../components/ui/status_badge.dart';
import '../components/ui/search_bar_widget.dart';
import '../components/ui/data_table_widget.dart';
import '../utils/app_spacing.dart';
import '../providers/purchase_provider.dart';
import '../models/purchase_return.dart';
import '../providers/purchase_return_provider.dart';
import '../screens/select_purchase_return_items_screen.dart';
import '../utils/app_colors.dart';
import 'package:firebase_auth/firebase_auth.dart' hide AuthProvider;
import 'package:pos/providers/auth_provider.dart' as myAuth;

class PurchasesScreen extends StatefulWidget {
  const PurchasesScreen({super.key});

  @override
  State<PurchasesScreen> createState() => _PurchasesScreenState();
}

class _PurchasesScreenState extends State<PurchasesScreen> {
  final TextEditingController _searchController = TextEditingController();
  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    super.initState();
    _searchController.addListener(_applyFilter);

    // Load initial data
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final purchaseProvider = context.read<PurchaseProvider>();
      final supplierProvider = context.read<SupplierProvider>();
      final productProvider = context.read<ProductProvider>();

      purchaseProvider.loadInitialPurchases();

      // Load suppliers
      supplierProvider.getSuppliersStream().listen((suppliers) {
        supplierProvider.setSuppliers(suppliers);
      });

      // Load products
      final vendorId = _getCurrentVendorId();
      productProvider.loadProducts(vendorId);
    });

    // Setup scroll listener for pagination
    _scrollController.addListener(_onScroll);
  }

  String _getCurrentVendorId() {
    return FirebaseAuth.instance.currentUser?.uid ?? '';
  }

  @override
  void dispose() {
    _searchController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _applyFilter() {
    final provider = context.read<PurchaseProvider>();
    provider.searchPurchases(_searchController.text);
  }

  void _onScroll() {
    if (_scrollController.position.pixels ==
        _scrollController.position.maxScrollExtent) {
      _loadMorePurchases();
    }
  }

  void _loadMorePurchases() async {
    final purchaseProvider = context.read<PurchaseProvider>();
    if (!purchaseProvider.isLoading && purchaseProvider.hasMore) {
      await purchaseProvider.loadMorePurchases();
    }
  }

  Future<void> _deletePurchase(String purchaseId) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Purchase'),
        content: const Text('Are you sure you want to delete this purchase?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(context).pop(true),
            child: const Text('Delete'),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      final provider = context.read<PurchaseProvider>();
      await provider.deletePurchase(purchaseId);
    }
  }

  // Add purchase return methods
  Future<void> _returnAllItems(Purchase purchase) async {
    final authProvider = context.read<myAuth.AuthProvider>();
    final purchaseReturnProvider = context.read<PurchaseReturnProvider>();
    final reason = await _showReasonDialog();

    if (reason == null) return; // User cancelled

    try {
      // Create purchase return items for all products
      final returnItems = purchase.items
          .map(
            (item) => PurchaseReturnItem(
              productId: item.productId,
              productName: item.productName,
              originalPrice: item.unitPrice,
              returnedQuantity: item.quantity,
              refundAmount: item.total,
            ),
          )
          .toList();

      // Calculate total refund
      final totalRefund = returnItems.fold(
        0.0,
        (sum, item) => sum + item.refundAmount,
      );

      // Create purchase return
      final purchaseReturn = PurchaseReturn(
        id: '', // Will be auto-generated by service
        vendorId: authProvider.currentUser!.id,
        originalPurchaseId: purchase.id,
        supplierId: purchase.supplierId,
        supplierName: purchase.supplierName,
        items: returnItems,
        totalRefund: totalRefund,
        reason: reason,
        createdAt: DateTime.now(),
      );

      await purchaseReturnProvider.createPurchaseReturn(
        authProvider.currentUser!.id,
        purchaseReturn,
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            duration: Duration(seconds: 1),
            content: Text(
              'Return processed successfully for ${totalRefund.toStringAsFixed(0)}',
            ),
            backgroundColor: AppColors.success,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            duration: Duration(seconds: 1),
            content: Text('Failed to process return: $e'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    }
  }

  Future<void> _returnSelectedItems(Purchase purchase) async {
    final result = await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) =>
            SelectPurchaseReturnItemsScreen(purchase: purchase),
      ),
    );

    if (result == null) return; // User cancelled

    final authProvider = context.read<myAuth.AuthProvider>();
    final purchaseReturnProvider = context.read<PurchaseReturnProvider>();
    final List<String> selectedProductIds = result['selectedProductIds'];
    final String reason = result['reason'];

    try {
      // Create purchase return items only for selected products
      final returnItems = purchase.items
          .where((item) => selectedProductIds.contains(item.productId))
          .map(
            (item) => PurchaseReturnItem(
              productId: item.productId,
              productName: item.productName,
              originalPrice: item.unitPrice,
              returnedQuantity: item.quantity,
              refundAmount: item.total,
            ),
          )
          .toList();

      // Calculate total refund
      final totalRefund = returnItems.fold(
        0.0,
        (sum, item) => sum + item.refundAmount,
      );

      // Create purchase return
      final purchaseReturn = PurchaseReturn(
        id: '', // Will be auto-generated by service
        vendorId: authProvider.currentUser!.id,
        originalPurchaseId: purchase.id,
        supplierId: purchase.supplierId,
        supplierName: purchase.supplierName,
        items: returnItems,
        totalRefund: totalRefund,
        reason: reason,
        createdAt: DateTime.now(),
      );

      await purchaseReturnProvider.createPurchaseReturn(
        authProvider.currentUser!.id,
        purchaseReturn,
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            duration: Duration(seconds: 1),
            content: Text(
              'Return processed successfully for ${totalRefund.toStringAsFixed(0)}',
            ),
            backgroundColor: AppColors.success,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            duration: Duration(seconds: 1),
            content: Text('Failed to process return: $e'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    }
  }

  Future<String?> _showReasonDialog() async {
    final TextEditingController reasonController = TextEditingController();

    return showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Reason for Return'),
        content: TextField(
          controller: reasonController,
          decoration: const InputDecoration(
            hintText: 'Enter reason for returning items...',
            border: OutlineInputBorder(),
          ),
          maxLines: 3,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () {
              if (reasonController.text.isNotEmpty) {
                Navigator.pop(context, reasonController.text);
              }
            },
            child: const Text('Confirm'),
          ),
        ],
      ),
    );
  }

  void _showPurchaseDetails(Purchase purchase) {
    showDialog(
      context: context,
      builder: (context) => Dialog(
        backgroundColor: const Color(0xFFFDFDFE),
        surfaceTintColor: Colors.transparent,
        insetPadding: const EdgeInsets.all(AppSpacing.lg),
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 800),
          child: Padding(
            padding: const EdgeInsets.all(AppSpacing.lg),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  'Purchase Details',
                  style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: AppSpacing.md),
                Text('Purchase ID: ${purchase.id.substring(0, 6)}'),
                Text('Supplier: ${purchase.supplierName}'),
                Text(
                  'Date: ${purchase.date.toLocal().toString().split(' ').first}',
                ),
                Text('Total: ${purchase.total.toStringAsFixed(0)}'),
                const SizedBox(height: AppSpacing.sm),
                const Divider(),
                const SizedBox(height: AppSpacing.sm),
                Text(
                  'Products',
                  style: Theme.of(context).textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: AppSpacing.md),
                Expanded(
                  child: SingleChildScrollView(
                    child: DataTable(
                      columns: const [
                        DataColumn(label: Text('Product')),
                        DataColumn(label: Text('Price'), numeric: true),
                        DataColumn(label: Text('Qty'), numeric: true),
                        DataColumn(label: Text('Subtotal'), numeric: true),
                      ],
                      rows: purchase.items.map((item) {
                        return DataRow(
                          cells: [
                            DataCell(Text(item.productName)),
                            DataCell(Text(item.unitPrice.toStringAsFixed(0))),
                            DataCell(Text('${item.quantity}')),
                            DataCell(Text(item.total.toStringAsFixed(0))),
                          ],
                        );
                      }).toList(),
                    ),
                  ),
                ),
                const SizedBox(height: AppSpacing.lg),
                Align(
                  alignment: Alignment.centerRight,
                  child: CustomButton(
                    text: 'Close',
                    variant: ButtonVariant.text,
                    onPressed: () => Navigator.pop(context),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _rowActions(Purchase purchase) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        IconButton(
          tooltip: 'View Details',
          icon: const Icon(Icons.visibility, size: 16),
          onPressed: () => _showPurchaseDetails(purchase),
          style: IconButton.styleFrom(
            backgroundColor: AppColors.primary.withOpacity(0.1),
            foregroundColor: AppColors.primary,
          ),
        ),
        const SizedBox(width: AppSpacing.xs),
        IconButton(
          tooltip: 'Return All Items',
          icon: const Icon(Icons.all_inbox, size: 16),
          onPressed: () => _returnAllItems(purchase),
          style: IconButton.styleFrom(
            backgroundColor: AppColors.success.withOpacity(0.1),
            foregroundColor: AppColors.success,
          ),
        ),
        const SizedBox(width: AppSpacing.xs),
        IconButton(
          tooltip: 'Select Items to Return',
          icon: const Icon(Icons.checklist, size: 16),
          onPressed: () => _returnSelectedItems(purchase),
          style: IconButton.styleFrom(
            backgroundColor: AppColors.warning.withOpacity(0.1),
            foregroundColor: AppColors.warning,
          ),
        ),
        const SizedBox(width: AppSpacing.xs),
        IconButton(
          icon: const Icon(Icons.delete, size: 16),
          onPressed: () => _deletePurchase(purchase.id),
          style: IconButton.styleFrom(
            backgroundColor: AppColors.error.withOpacity(0.1),
            foregroundColor: AppColors.error,
          ),
        ),
      ],
    );
  }

  Widget _buildContent(PurchaseProvider provider, AppLocalizations l10n) {
    if (provider.isLoading && provider.purchases.isEmpty) {
      return _buildShimmerTable();
    }

    if (provider.error != null) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.error, size: 64, color: AppColors.error),
            const SizedBox(height: AppSpacing.md),
            Text('Error: ${provider.error}'),
            const SizedBox(height: AppSpacing.md),
            CustomButton(
              text: 'Retry',
              onPressed: () => provider.loadInitialPurchases(),
              variant: ButtonVariant.filled,
            ),
          ],
        ),
      );
    }

    final purchases = provider.purchases;

    if (purchases.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(Icons.shopping_cart, size: 64, color: Colors.grey),
            const SizedBox(height: AppSpacing.md),
            Text(
              _searchController.text.isEmpty
                  ? 'No purchases found'
                  : 'No purchases found for "${_searchController.text}"',
              style: TextStyle(fontSize: 18, color: Colors.grey.shade600),
            ),
            if (_searchController.text.isEmpty) ...[
              const SizedBox(height: AppSpacing.md),
              CustomButton(
                text: 'Create First Purchase',
                onPressed: () {
                  showPurchaseDialog(
                    context,
                    onSave: (newPurchase) async {
                      final provider = context.read<PurchaseProvider>();
                      await provider.addPurchase(newPurchase);
                    },
                  );
                },
                variant: ButtonVariant.filled,
              ),
            ],
          ],
        ),
      );
    }

    return NotificationListener<ScrollNotification>(
      onNotification: (scrollNotification) {
        if (scrollNotification is ScrollEndNotification &&
            _scrollController.position.pixels ==
                _scrollController.position.maxScrollExtent) {
          _loadMorePurchases();
        }
        return false;
      },
      child: SingleChildScrollView(
        controller: _scrollController,
        child: DataTableWidget(
          columns: const [
            DataColumn(label: Text('#')),
            DataColumn(label: Text('Supplier')),
            DataColumn(label: Text('Items')),
            DataColumn(label: Text('Total')),
            DataColumn(label: Text('Date')),
            DataColumn(label: Text('Actions')),
          ],
          rows: purchases.asMap().entries.map((entry) {
            final index = entry.key + 1; // Serial numbers start from 1
            final purchase = entry.value;

            return DataRow(
              cells: [
                DataCell(Text('$index')), // <-- Serial number column
                DataCell(Text(purchase.supplierName)),
                DataCell(
                  SizedBox(
                    width: 200,
                    child: Tooltip(
                      message: purchase.items
                          .map((item) => item.productName)
                          .join(', '),
                      child: Text(
                        purchase.items
                            .map((item) => item.productName)
                            .join(', '),
                        maxLines: 2,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                  ),
                ),
                DataCell(Text(purchase.total.toStringAsFixed(0))),
                DataCell(
                  Text(
                    DateFormat('d MMM yyyy').format(purchase.date.toLocal()),
                  ),
                ),
                DataCell(_rowActions(purchase)),
              ],
            );
          }).toList(),
          mobileItemBuilder: (context, index) {
            final purchase = purchases[index];
            return CustomCard(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: Text(
                          'Purchase #${purchase.id.substring(0, 8)}...',
                          style: Theme.of(context).textTheme.titleMedium
                              ?.copyWith(fontWeight: FontWeight.w600),
                        ),
                      ),
                      StatusBadge(text: purchase.status),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.xs),
                  Text('Supplier: ${purchase.supplierName}'),
                  const SizedBox(height: AppSpacing.xs),
                  Text(
                    'Items: ${purchase.items.map((item) => item.productName).join(', ')}',
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                  const SizedBox(height: AppSpacing.xs),
                  Text('Total: ${purchase.total.toStringAsFixed(0)}'),
                  const SizedBox(height: AppSpacing.xs),
                  Text(
                    'Date: ${'${purchase.date.toLocal()}'.split(' ').first}',
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [_rowActions(purchase)],
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }

  Widget _buildShimmerTable() {
    return DataTableWidget(
      columns: List.generate(
        6,
        (index) => DataColumn(label: ShimmerEffect(width: 80, height: 20)),
      ),
      rows: List.generate(
        5,
        (index) => DataRow(
          cells: List.generate(
            6,
            (index) => DataCell(
              index == 5
                  ? Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        ShimmerEffect(
                          width: 36,
                          height: 36,
                          borderRadius: BorderRadius.circular(18),
                        ),
                        SizedBox(width: AppSpacing.xs),
                        ShimmerEffect(
                          width: 36,
                          height: 36,
                          borderRadius: BorderRadius.circular(18),
                        ),
                        SizedBox(width: AppSpacing.xs),
                        ShimmerEffect(
                          width: 36,
                          height: 36,
                          borderRadius: BorderRadius.circular(18),
                        ),
                        SizedBox(width: AppSpacing.xs),
                        ShimmerEffect(
                          width: 36,
                          height: 36,
                          borderRadius: BorderRadius.circular(18),
                        ),
                      ],
                    )
                  : ShimmerEffect(width: 80, height: 20),
            ),
          ),
        ),
      ),
      mobileItemBuilder: (context, index) {
        return CustomCard(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Expanded(child: ShimmerEffect(width: 120, height: 20)),
                  ShimmerEffect(
                    width: 60,
                    height: 24,
                    borderRadius: BorderRadius.circular(12),
                  ),
                ],
              ),
              SizedBox(height: AppSpacing.sm),
              ShimmerEffect(width: 150, height: 16),
              SizedBox(height: AppSpacing.xs),
              ShimmerEffect(width: 200, height: 16),
              SizedBox(height: AppSpacing.xs),
              ShimmerEffect(width: 80, height: 16),
              SizedBox(height: AppSpacing.xs),
              ShimmerEffect(width: 100, height: 16),
              SizedBox(height: AppSpacing.sm),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ShimmerEffect(
                    width: 36,
                    height: 36,
                    borderRadius: BorderRadius.circular(18),
                  ),
                  SizedBox(width: AppSpacing.xs),
                  ShimmerEffect(
                    width: 36,
                    height: 36,
                    borderRadius: BorderRadius.circular(18),
                  ),
                  SizedBox(width: AppSpacing.xs),
                  ShimmerEffect(
                    width: 36,
                    height: 36,
                    borderRadius: BorderRadius.circular(18),
                  ),
                  SizedBox(width: AppSpacing.xs),
                  ShimmerEffect(
                    width: 36,
                    height: 36,
                    borderRadius: BorderRadius.circular(18),
                  ),
                ],
              ),
            ],
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final purchaseProvider = context.watch<PurchaseProvider>();

    return Padding(
      padding: EdgeInsets.symmetric(horizontal: 20, vertical: 10),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      l10n.purchases,
                      style: Theme.of(context).textTheme.headlineMedium
                          ?.copyWith(
                            fontWeight: FontWeight.w700,
                            color: Theme.of(context).colorScheme.onSurface,
                          ),
                    ),
                    const SizedBox(height: AppSpacing.xs),
                    Text(
                      'Track your purchase orders',
                      style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        color: Theme.of(
                          context,
                        ).textTheme.bodyMedium?.color?.withOpacity(0.8),
                      ),
                    ),
                  ],
                ),
              ),
              CustomButton(
                text: 'New Purchase',
                icon: Icons.add_shopping_cart,
                onPressed: () {
                  showPurchaseDialog(
                    context,
                    onSave: (newPurchase) async {
                      final provider = context.read<PurchaseProvider>();
                      await provider.addPurchase(newPurchase);
                    },
                  );
                },
              ),
            ],
          ),
          const SizedBox(height: AppSpacing.md),
          SearchBarWidget(
            controller: _searchController,
            hint: 'Search purchases...',
            onChanged: (_) => _applyFilter(),
            onClear: () {
              _searchController.clear();
              _applyFilter();
            },
          ),
          const SizedBox(height: AppSpacing.sm),
          Expanded(child: _buildContent(purchaseProvider, l10n)),
        ],
      ),
    );
  }
}
