import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:pos/models/sale.dart';
import 'package:pos/models/table.dart';
import 'package:pos/providers/auth_provider.dart';
import 'package:pos/providers/sale_provider.dart';
import 'package:pos/providers/table_provider.dart';
import 'package:pos/routes/app_router.dart';

const _purple=Color(0xFF6C3BFF),_line=Color(0xFFE5E7EB),_ink=Color(0xFF111827),_muted=Color(0xFF6B7280),_soft=Color(0xFFF9FAFB);

class RestaurantDashboardScreen extends StatefulWidget{const RestaurantDashboardScreen({super.key});@override State<RestaurantDashboardScreen> createState()=>_RestaurantDashboardScreenState();}
class _RestaurantDashboardScreenState extends State<RestaurantDashboardScreen>{
 bool _started=false,_prefsLoaded=false; List<String> _order=List.from(_defaults); Set<String> _visible=Set.from(_defaults);
 static const _defaults=<String>['sales','orders','tables','kot','payments','pra','activity','leakage','expenses','store','branches','cameras'];
 static const _labels=<String,String>{'sales':"Today's Sales",'orders':"Today's Receipts",'tables':'Live Tables','kot':'Live KOT','payments':'Payments','pra':'PRA Monitor','activity':'Live Activity','leakage':'Leakage & Theft','expenses':'Expenses','store':'Store','branches':'Branches','cameras':'Cameras'};
 @override void didChangeDependencies(){super.didChangeDependencies();if(!_started){_started=true;final u=context.read<AuthProvider>().currentUser;if(u!=null){context.read<TableProvider>().loadTables();context.read<SaleProvider>().fetchSales(u.id);}}if(!_prefsLoaded){_prefsLoaded=true;_loadPrefs();}}
 DocumentReference<Map<String,dynamic>>? get _prefsRef{final u=context.read<AuthProvider>().currentUser;if(u==null)return null;final k=(u.authUid??u.id).replaceAll('/','_');return FirebaseFirestore.instance.collection('vendors').doc(u.id).collection('dashboardPreferences').doc(k);}
 Future<void> _loadPrefs()async{try{final d=await _prefsRef?.get(),x=d?.data();if(x==null||!mounted)return;final o=(x['order']as List?)?.map((e)=>e.toString()).where(_labels.containsKey).toList()??<String>[];final v=(x['visible']as List?)?.map((e)=>e.toString()).where(_labels.containsKey).toSet()??<String>{};setState((){_order=[...o,..._defaults.where((e)=>!o.contains(e))];_visible=v.isEmpty?Set.from(_defaults):v;});}catch(_){}}
 Future<void> _savePrefs()async{try{await _prefsRef?.set({'order':_order,'visible':_visible.toList(),'updatedAt':FieldValue.serverTimestamp()},SetOptions(merge:true));}catch(_){}}
 Future<void> _customize()async{final t=Set<String>.from(_visible);final r=await showDialog<Set<String>>(context:context,builder:(c)=>StatefulBuilder(builder:(_,s)=>AlertDialog(backgroundColor:Colors.white,title:const Text('Customize dashboard'),content:SizedBox(width:500,child:SingleChildScrollView(child:Column(children:_defaults.map((id)=>CheckboxListTile(value:t.contains(id),dense:true,title:Text(_labels[id]!),onChanged:(v)=>s(()=>v==true?t.add(id):t.remove(id)))).toList()))),actions:[TextButton(onPressed:()=>s((){t..clear()..addAll(_defaults);}),child:const Text('Add all')),TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,t),child:const Text('Save'))])));if(r!=null&&mounted){setState(()=>_visible=r);_savePrefs();}}
 void _hide(String id){setState(()=>_visible.remove(id));_savePrefs();} void _move(String a,String b){if(a==b)return;final x=_order.indexOf(a),y=_order.indexOf(b);if(x<0||y<0)return;setState((){final z=_order.removeAt(x);_order.insert(y,z);});_savePrefs();}
 bool _today(DateTime d){final n=DateTime.now();return d.year==n.year&&d.month==n.month&&d.day==n.day;}
 @override Widget build(BuildContext context){final u=context.watch<AuthProvider>().currentUser;if(u==null)return const Center(child:CircularProgressIndicator());final tables=context.watch<TableProvider>().tables,sales=context.watch<SaleProvider>().sales,today=sales.where((s)=>_today(s.createdAt)).toList();final revenue=today.fold<double>(0,(a,b)=>a+b.total),vendor=FirebaseFirestore.instance.collection('vendors').doc(u.id);
 return StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:vendor.collection('tableOrders').snapshots(),builder:(context,snap){final orders=snap.data?.docs??const[];return ColoredBox(color:Colors.white,child:SingleChildScrollView(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(u.restaurantName,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:_ink)),const SizedBox(height:3),const Row(children:[Icon(Icons.circle,size:8,color:Color(0xFF10B981)),SizedBox(width:6),Text('LIVE • Updates automatically',style:TextStyle(fontSize:11,color:_muted))])])),OutlinedButton.icon(onPressed:_customize,icon:const Icon(Icons.dashboard_customize_outlined,size:17),label:const Text('Customize'))]),const SizedBox(height:16),LayoutBuilder(builder:(_,c){final cols=c.maxWidth>1180?3:c.maxWidth>760?2:1,w=(c.maxWidth-(cols-1)*12)/cols;return Wrap(spacing:12,runSpacing:12,children:_order.where(_visible.contains).map((id)=>DragTarget<String>(onWillAcceptWithDetails:(d)=>d.data!=id,onAcceptWithDetails:(d)=>_move(d.data,id),builder:(_,__,___)=>LongPressDraggable<String>(data:id,feedback:Material(color:Colors.transparent,child:SizedBox(width:w,child:_widget(id,revenue,today,tables,orders,sales))),child:SizedBox(width:w,child:_widget(id,revenue,today,tables,orders,sales))))).toList());})])));});}
 Widget _widget(String id,double revenue,List<Sale> today,List<RestaurantTable> tables,List<QueryDocumentSnapshot<Map<String,dynamic>>> orders,List<Sale> sales){final active=tables.where((t)=>t.status!=TableStatus.empty).length,making=orders.where((d)=>['making','open','sent'].contains((d.data()['status']??'').toString().toLowerCase())).length,ready=orders.where((d)=>(d.data()['status']??'').toString().toLowerCase()=='ready').length,pra=today.where((s)=>(s.praInvoiceNo??'').isNotEmpty).length,reprints=today.where((s)=>s.receiptPrintCount>1).length;
 switch(id){case'sales':return _metric(id,"Today's Sales",'Rs ${revenue.toStringAsFixed(0)}',Icons.account_balance_wallet_outlined,()=>context.go(AppRouter.sales));case'orders':return _metric(id,"Today's Receipts",'${today.length}',Icons.receipt_long_outlined,()=>context.go(AppRouter.sales));case'tables':return _panel(id,'Live Tables','$active in service • ${tables.length-active} available',_tables(tables),()=>context.go(AppRouter.tables));case'kot':return _panel(id,'Live KOT','$making making • $ready ready',_kots(orders),()=>context.go(AppRouter.orders));case'payments':return _panel(id,'Payments','Live completed receipts',_payments(today),()=>context.go(AppRouter.sales));case'pra':return _metric(id,'PRA Monitor','$pra / ${today.length} fiscalized',Icons.verified_user_outlined,()=>context.go(AppRouter.praSettings));case'activity':return _panel(id,'Live Activity','Latest operational changes',_activity(orders,sales),()=>context.go(AppRouter.orders));case'leakage':return _panel(id,'Leakage & Theft','$reprints reprint alerts',_leakage(today,orders),(){});case'expenses':return _action(id,'Expenses','Operating costs and expense controls',Icons.payments_outlined,()=>context.go(AppRouter.expenses));case'store':return _action(id,'Store','Stock issues and movement control',Icons.storefront_outlined,()=>context.go(AppRouter.storeOut));case'branches':return _action(id,'Branches','Multi-branch monitoring',Icons.account_tree_outlined,()=>context.go(AppRouter.branches));case'cameras':return _action(id,'Cameras','Connect CCTV / NVR feeds',Icons.videocam_outlined,()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Configure the restaurant CCTV/NVR stream to enable live cameras.'))));default:return const SizedBox.shrink();}}
 Widget _metric(String id,String t,String v,IconData i,VoidCallback tap)=>_Card(title:t,subtitle:'Realtime',onHide:()=>_hide(id),onTap:tap,height:118,child:Row(children:[Container(width:44,height:44,decoration:BoxDecoration(color:_purple.withValues(alpha:.09),borderRadius:BorderRadius.circular(10)),child:Icon(i,color:_purple)),const SizedBox(width:12),Expanded(child:Text(v,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:_ink)))]));
 Widget _action(String id,String t,String s,IconData i,VoidCallback tap)=>_Card(title:t,subtitle:s,onHide:()=>_hide(id),onTap:tap,height:145,child:Align(alignment:Alignment.centerLeft,child:Icon(i,size:34,color:_purple)));
 Widget _panel(String id,String t,String s,Widget w,VoidCallback tap)=>_Card(title:t,subtitle:s,onHide:()=>_hide(id),onTap:tap,height:285,child:w);
 Widget _tables(List<RestaurantTable>x)=>ListView(children:x.take(6).map((t)=>_row('Table ${t.tableNumber}',t.statusString.toUpperCase(),t.status==TableStatus.empty?const Color(0xFF10B981):const Color(0xFFF59E0B))).toList());
 Widget _kots(List<QueryDocumentSnapshot<Map<String,dynamic>>>x)=>ListView(children:x.take(6).map((d){final a=d.data(),s=(a['status']??'open').toString();return _row('Table ${a['tableNumber']??a['tableId']??'-'}',s.toUpperCase(),s=='ready'?const Color(0xFF10B981):const Color(0xFFF59E0B));}).toList());
 Widget _payments(List<Sale>x)=>ListView(children:x.take(6).map((s)=>_row('Rs ${s.total.toStringAsFixed(0)}',s.paymentMethod.toUpperCase(),_purple)).toList());
 Widget _activity(List<QueryDocumentSnapshot<Map<String,dynamic>>>o,List<Sale>s)=>ListView(children:[...o.take(3).map((d){final x=d.data();return _row('Table ${x['tableNumber']??x['tableId']??'-'}','${x['status']??'UPDATED'}'.toUpperCase(),_purple);}),...s.take(3).map((x)=>_row('Receipt ${x.id.length>12?x.id.substring(0,12):x.id}','PAID ${x.paymentMethod.toUpperCase()}',const Color(0xFF10B981)))]);
 Widget _leakage(List<Sale>s,List<QueryDocumentSnapshot<Map<String,dynamic>>>o){final a=<Widget>[];for(final x in s.where((e)=>e.receiptPrintCount>1).take(4)){a.add(_row('Receipt reprinted','${x.receiptPrintCount} PRINTS',const Color(0xFFEF4444)));}for(final x in o.where((e)=>(e.data()['status']??'')=='cancelled').take(3)){a.add(_row('Cancelled order','REVIEW',const Color(0xFFEF4444)));}return ListView(children:a.isEmpty?[const Padding(padding:EdgeInsets.all(12),child:Text('No current leakage alerts',style:TextStyle(fontSize:11,color:_muted)))]:a);}
 Widget _row(String l,String r,Color c)=>Container(margin:const EdgeInsets.only(bottom:7),padding:const EdgeInsets.symmetric(horizontal:10,vertical:9),decoration:BoxDecoration(color:_soft,borderRadius:BorderRadius.circular(8)),child:Row(children:[Expanded(child:Text(l,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700,color:_ink))),Text(r,style:TextStyle(fontSize:9,fontWeight:FontWeight.w800,color:c))]));}
class _Card extends StatelessWidget{final String title,subtitle;final VoidCallback onHide,onTap;final double height;final Widget child;const _Card({required this.title,required this.subtitle,required this.onHide,required this.onTap,required this.height,required this.child});@override Widget build(BuildContext context)=>Container(height:height,decoration:BoxDecoration(color:Colors.white,border:Border.all(color:_line),borderRadius:BorderRadius.circular(12)),child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(14,10,6,5),child:Row(children:[Expanded(child:InkWell(onTap:onTap,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:13,fontWeight:FontWeight.w800,color:_ink)),Text(subtitle,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:9.5,color:_muted))]))),IconButton(visualDensity:VisualDensity.compact,onPressed:onHide,icon:const Icon(Icons.close_rounded,size:15,color:Color(0xFF9CA3AF)))])),Expanded(child:Padding(padding:const EdgeInsets.fromLTRB(14,2,14,12),child:child))]));}
